/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Mandel */

#ifndef _Included_Mandel
#define _Included_Mandel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Mandel
 * Method:    kernelWrapper
 * Signature: ([BIIDDDDIII)V
 */
JNIEXPORT void JNICALL Java_mandel_kernelWrapper
  (JNIEnv *, jobject, jbyteArray, jint, jint, jdouble, jdouble, jdouble, jdouble, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
